name: noteswap
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  file_picker: ^8.0.7
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10+1
  go_router: ^14.2.2
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  http: ^1.2.2
  image_picker: ^1.1.2
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.3.5
  validators: ^3.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  custom_lint: ^0.6.4
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  build_runner: ^2.4.11
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/school/
    - assets/onboard/
  fonts:
    - family: ClashDisplay
      fonts:
        - asset: fonts/ClashDisplay-Regular.otf
        - asset: fonts/ClashDisplay-Bold.otf
        - asset: fonts/ClashDisplay-ExtraLight.otf
        - asset: fonts/ClashDisplay-Light.otf
        - asset: fonts/ClashDisplay-Medium.otf
        - asset: fonts/ClashDisplay-SemiBold.otf